// GENERATED by `pnpm --filter @br/capture-worker build:function` from
// apps/capture-worker/src/edge/entry.ts (T-034). Do not edit; change the sources and rebuild.
// A unit test (apps/capture-worker/test/function-bundle.test.ts) fails when this is stale.

// src/log.ts
var ORDER = { debug: 10, info: 20, warn: 30, error: 40 };
function isLogLevel(s) {
  return s in ORDER;
}
function createLogger(opts = {}) {
  const min = ORDER[opts.level ?? "info"];
  const write = opts.write ?? ((line) => {
    if (typeof process === "undefined") console.log(line);
    else process.stdout.write(`${line}
`);
  });
  const now = opts.now ?? (() => /* @__PURE__ */ new Date());
  const base = opts.base ?? {};
  const emit = (level, msg, fields) => {
    if (ORDER[level] < min) return;
    let line;
    try {
      line = JSON.stringify({ t: now().toISOString(), level, msg, ...base, ...fields });
    } catch {
      line = JSON.stringify({ t: now().toISOString(), level, msg, ...base, unserializable: true });
    }
    write(line);
    if (level === "error" && opts.onError) {
      try {
        opts.onError(msg, { ...base, ...fields });
      } catch {
      }
    }
  };
  return {
    debug: (m, f) => {
      emit("debug", m, f);
    },
    info: (m, f) => {
      emit("info", m, f);
    },
    warn: (m, f) => {
      emit("warn", m, f);
    },
    error: (m, f) => {
      emit("error", m, f);
    },
    child: (fields) => createLogger({ ...opts, base: { ...base, ...fields } })
  };
}
var silentLogger = createLogger({
  write: () => void 0
});
function errorMessage(e) {
  if (e instanceof Error) return e.message;
  return String(e);
}

// src/budget.ts
var FREE_BROWSER_MS_PER_DAY = 6e5;
var DEFAULT_BROWSER_BUDGET_MS = 57e4;
var DEFAULT_BROWSER_RESERVE_MS = 2e4;
var DailyBrowserBudget = class {
  constructor(backend, opts, log) {
    this.backend = backend;
    this.opts = opts;
    this.log = log;
  }
  backend;
  opts;
  log;
  async reserve() {
    const state = await this.backend.reserveBrowserTime(this.opts.reserveMs, this.opts.limitMs);
    if (!state.granted) {
      this.log.info("budget.spent", {
        day: state.day,
        usedMs: state.usedMs,
        reservedMs: state.reservedMs,
        limitMs: state.limitMs
      });
      return null;
    }
    return { day: state.day, reservedMs: this.opts.reserveMs };
  }
  async settle(ticket, usage) {
    try {
      await this.backend.settleBrowserTime(
        ticket.day,
        ticket.reservedMs,
        Math.max(0, Math.round(usage.browserMs)),
        usage.rateLimited
      );
    } catch (e) {
      this.log.error("budget.settle_failed", { day: ticket.day, error: errorMessage(e) });
    }
  }
};

// src/renderer.ts
var RenderError = class extends Error {
  constructor(code, message, extra = {}) {
    super(`${code}: ${message}`);
    this.code = code;
    this.extra = extra;
    this.name = "RenderError";
  }
  code;
  extra;
};

// src/webp.ts
var WebpError = class extends Error {
  constructor(message) {
    super(`webp: ${message}`);
    this.name = "WebpError";
  }
};
var VP8X_FLAG_ALPHA = 16;
var VP8X_FLAG_ANIMATION = 2;
function fourcc(b, at) {
  return String.fromCharCode(b[at] ?? 0, b[at + 1] ?? 0, b[at + 2] ?? 0, b[at + 3] ?? 0);
}
function u32le(b, at) {
  return ((b[at] ?? 0) | (b[at + 1] ?? 0) << 8 | (b[at + 2] ?? 0) << 16) + (b[at + 3] ?? 0) * 2 ** 24;
}
function u24le(b, at) {
  return (b[at] ?? 0) | (b[at + 1] ?? 0) << 8 | (b[at + 2] ?? 0) << 16;
}
function readChunks(bytes) {
  if (bytes.length < 20 || fourcc(bytes, 0) !== "RIFF" || fourcc(bytes, 8) !== "WEBP") {
    throw new WebpError("not a RIFF/WEBP file");
  }
  const riffEnd = 8 + u32le(bytes, 4);
  if (riffEnd > bytes.length) throw new WebpError("truncated (RIFF size past the end)");
  const chunks = [];
  let at = 12;
  while (at < riffEnd) {
    if (at + 8 > riffEnd) throw new WebpError("truncated chunk header");
    const size = u32le(bytes, at + 4);
    const start = at + 8;
    if (start + size > riffEnd) throw new WebpError(`chunk ${fourcc(bytes, at)} past the end`);
    chunks.push({ fourcc: fourcc(bytes, at), data: bytes.subarray(start, start + size) });
    at = start + size + size % 2;
    if (chunks.length > 64) throw new WebpError("too many chunks");
  }
  return chunks;
}
function vp8Size(data) {
  if (data.length < 10) throw new WebpError("VP8 bitstream too short");
  if (((data[0] ?? 1) & 1) !== 0) throw new WebpError("VP8 bitstream is not a key frame");
  if (data[3] !== 157 || data[4] !== 1 || data[5] !== 42) {
    throw new WebpError("VP8 start code missing");
  }
  return {
    width: ((data[6] ?? 0) | (data[7] ?? 0) << 8) & 16383,
    height: ((data[8] ?? 0) | (data[9] ?? 0) << 8) & 16383
  };
}
function vp8lSize(data) {
  if (data.length < 5 || data[0] !== 47) throw new WebpError("VP8L signature missing");
  const bits = u32le(data, 1);
  const version = Math.floor(bits / 2 ** 29) & 7;
  if (version !== 0) throw new WebpError("VP8L version is not 0");
  return {
    width: (bits & 16383) + 1,
    height: (bits >>> 14 & 16383) + 1,
    alpha: (bits >>> 28 & 1) === 1
  };
}
function parse(bytes) {
  const chunks = readChunks(bytes);
  const names = chunks.map((c) => c.fourcc);
  if (names.includes("ANIM") || names.includes("ANMF")) throw new WebpError("animated");
  const images = chunks.filter((c) => c.fourcc === "VP8 " || c.fourcc === "VP8L");
  const [image] = images;
  if (images.length !== 1 || !image) {
    throw new WebpError(`expected one image, found ${String(images.length)}`);
  }
  const alphs = chunks.filter((c) => c.fourcc === "ALPH");
  if (alphs.length > 1) throw new WebpError("several ALPH chunks");
  const alph = alphs[0] ?? null;
  const vp8x = chunks.find((c) => c.fourcc === "VP8X") ?? null;
  if (vp8x && chunks[0] !== vp8x) throw new WebpError("VP8X is not the first chunk");
  if (!vp8x && chunks.length !== 1) throw new WebpError("extra chunks without VP8X");
  let width;
  let height;
  let alpha;
  if (image.fourcc === "VP8L") {
    if (alph) throw new WebpError("ALPH next to a lossless image");
    ({ width, height, alpha } = vp8lSize(image.data));
  } else {
    ({ width, height } = vp8Size(image.data));
    alpha = alph !== null;
  }
  if (width === 0 || height === 0) throw new WebpError("zero-sized image");
  if (vp8x) {
    if (vp8x.data.length < 10) throw new WebpError("VP8X too short");
    if (((vp8x.data[0] ?? 0) & VP8X_FLAG_ANIMATION) !== 0) throw new WebpError("animated");
    const cw = u24le(vp8x.data, 4) + 1;
    const ch = u24le(vp8x.data, 7) + 1;
    if (cw !== width || ch !== height) {
      throw new WebpError("VP8X canvas size differs from the image size");
    }
  }
  return {
    info: { width, height, lossless: image.fourcc === "VP8L", alpha, chunks: names },
    image,
    alph
  };
}
function parseWebp(bytes) {
  return parse(bytes).info;
}
function chunkBytes(fourccName, data) {
  const out = new Uint8Array(8 + data.length + data.length % 2);
  for (let i = 0; i < 4; i++) out[i] = fourccName.charCodeAt(i);
  new DataView(out.buffer).setUint32(4, data.length, true);
  out.set(data, 8);
  return out;
}
function sanitizeWebp(bytes, limits) {
  const { info, image, alph } = parse(bytes);
  if (info.width > limits.maxWidth || info.height > limits.maxHeight) {
    throw new WebpError(
      `${String(info.width)}×${String(info.height)} is larger than ${String(limits.maxWidth)}×${String(limits.maxHeight)}`
    );
  }
  const parts = [];
  if (alph) {
    const w = info.width - 1;
    const h = info.height - 1;
    const vp8x = new Uint8Array([
      VP8X_FLAG_ALPHA,
      0,
      0,
      0,
      w & 255,
      w >> 8 & 255,
      w >> 16 & 255,
      h & 255,
      h >> 8 & 255,
      h >> 16 & 255
    ]);
    parts.push(chunkBytes("VP8X", vp8x), chunkBytes("ALPH", alph.data));
  }
  parts.push(chunkBytes(image.fourcc, image.data));
  const body = parts.reduce((n, p) => n + p.length, 0);
  const out = new Uint8Array(12 + body);
  out.set([82, 73, 70, 70], 0);
  new DataView(out.buffer).setUint32(4, 4 + body, true);
  out.set([87, 69, 66, 80], 8);
  let at = 12;
  for (const p of parts) {
    out.set(p, at);
    at += p.length;
  }
  if (out.length > limits.maxBytes) {
    throw new WebpError(
      `${String(out.length)} bytes is over the ${String(limits.maxBytes)}-byte limit`
    );
  }
  return out;
}

// src/imaging.ts
var MAX_SCREENSHOT_BYTES = 2 * 1024 * 1024;
var SCREENSHOT_WEBP_QUALITY = 82;
var webpImaging = {
  screenshot(render, viewport) {
    if (render.format !== "webp") {
      return Promise.resolve({ ok: false, reason: `expected a WebP render, got ${render.format}` });
    }
    if (render.paint === "empty") {
      return Promise.resolve({
        ok: false,
        reason: "blank render (the capture page found nothing rendered in the build frame)"
      });
    }
    try {
      const info = parseWebp(render.image);
      if (info.width !== viewport.width || info.height !== viewport.height) {
        return Promise.resolve({
          ok: false,
          reason: `render is ${String(info.width)}×${String(info.height)}, not the viewport`
        });
      }
      return Promise.resolve({
        ok: true,
        webp: sanitizeWebp(render.image, {
          maxWidth: viewport.width,
          maxHeight: viewport.height,
          maxBytes: MAX_SCREENSHOT_BYTES
        })
      });
    } catch (e) {
      if (e instanceof WebpError) return Promise.resolve({ ok: false, reason: e.message });
      throw e;
    }
  },
  thumbnail(bytes, fit) {
    return Promise.resolve(
      sanitizeWebp(bytes, {
        maxWidth: fit.width,
        maxHeight: fit.height,
        maxBytes: MAX_SCREENSHOT_BYTES
      })
    );
  }
};

// src/browser-rendering.ts
var BROWSER_RENDERING_API_URL = "https://api.cloudflare.com/client/v4";
var CAPTURE_SIGNAL_SELECTOR = "html[data-br-capture]";
var FREE_PLAN_MIN_INTERVAL_MS = 1e4;
var DEFAULTS = {
  apiUrl: BROWSER_RENDERING_API_URL,
  capMs: 6e3,
  gotoTimeoutMs: 1e4,
  actionTimeoutMs: 1e4,
  quality: SCREENSHOT_WEBP_QUALITY,
  minIntervalMs: FREE_PLAN_MIN_INTERVAL_MS,
  maxInlineRetryAfterMs: 12e3,
  rateLimitRetries: 1,
  maxResponseBytes: 8 * 1024 * 1024
};
function snapshotRequestBody(req, opts = {}) {
  return {
    url: req.url,
    viewport: { width: req.viewport.width, height: req.viewport.height, deviceScaleFactor: 1 },
    gotoOptions: { waitUntil: "load", timeout: opts.gotoTimeoutMs ?? DEFAULTS.gotoTimeoutMs },
    waitForSelector: { selector: CAPTURE_SIGNAL_SELECTOR, timeout: opts.capMs ?? DEFAULTS.capMs },
    bestAttempt: true,
    actionTimeout: opts.actionTimeoutMs ?? DEFAULTS.actionTimeoutMs,
    screenshotOptions: { type: "webp", quality: opts.quality ?? DEFAULTS.quality, fullPage: false }
  };
}
function snapshotUrl(apiUrl, accountId) {
  return `${apiUrl.replace(/\/+$/, "")}/accounts/${encodeURIComponent(accountId)}/browser-rendering/snapshot?cacheTTL=0`;
}
function parseRetryAfter(value, nowMs) {
  if (value === null) return null;
  const v = value.trim();
  if (/^\d+$/.test(v)) return Number(v) * 1e3;
  const at = Date.parse(v);
  if (Number.isNaN(at)) return null;
  return Math.max(0, at - nowMs);
}
function browserMsHeader(headers) {
  const raw = headers.get("x-browser-ms-used");
  if (raw === null || !/^\d+(\.\d+)?$/.test(raw.trim())) return null;
  return Math.round(Number(raw));
}
var ENTITIES = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'" };
function decodeEntities(s) {
  return s.replace(/&(#\d+|#x[0-9a-f]+|[a-z]+);/gi, (m, e) => {
    if (e.startsWith("#x") || e.startsWith("#X"))
      return String.fromCodePoint(parseInt(e.slice(2), 16) || 65533);
    if (e.startsWith("#")) return String.fromCodePoint(Number(e.slice(1)) || 65533);
    return ENTITIES[e.toLowerCase()] ?? m;
  });
}
function htmlElementAttributes(html) {
  let i = 0;
  for (; ; ) {
    while (i < html.length && /\s/.test(html[i] ?? "")) i++;
    if (html.startsWith("<!--", i)) {
      const end = html.indexOf("-->", i + 4);
      if (end < 0) return null;
      i = end + 3;
    } else if (/^<!doctype/i.test(html.slice(i, i + 9))) {
      const end = html.indexOf(">", i);
      if (end < 0) return null;
      i = end + 1;
    } else {
      break;
    }
  }
  if (!/^<html[\s>/]/i.test(html.slice(i, i + 6))) return null;
  i += 5;
  const attrs = /* @__PURE__ */ new Map();
  const re = /\s*([^\s"'>/=]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+)))?|\s*\/?>/y;
  re.lastIndex = i;
  for (let n = 0; n < 200; n++) {
    const m = re.exec(html);
    if (!m) return attrs;
    if (m[1] === void 0) return attrs;
    const name = m[1].toLowerCase();
    if (!attrs.has(name)) attrs.set(name, decodeEntities(m[2] ?? m[3] ?? m[4] ?? ""));
  }
  return attrs;
}
function readCaptureReport(html) {
  const attrs = htmlElementAttributes(html);
  if (!attrs?.has("data-br-capture-page"))
    return { page: false, state: null, paint: null, detail: null };
  const state = attrs.get("data-br-capture");
  const paint = attrs.get("data-br-paint");
  const detail = attrs.get("data-br-capture-error");
  return {
    page: true,
    state: state === "ready" || state === "failed" ? state : null,
    paint: paint === "content" || paint === "empty" ? paint : null,
    detail: detail ? detail.slice(0, 300) : null
  };
}
function redact(message) {
  return message.replace(/\bhttps?:\/\/[^\s"'<>]+/g, (url) => {
    try {
      const u = new URL(url);
      return `${u.origin}${u.pathname}${u.search ? "?…" : ""}`;
    } catch {
      return "(url)";
    }
  });
}
function base64ToBytes(b64) {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
async function readLimited(res, max) {
  if (!res.body) return "";
  const reader = res.body.getReader();
  const chunks = [];
  let total = 0;
  for (; ; ) {
    const { done, value } = await reader.read();
    if (done) break;
    total += value.byteLength;
    if (total > max) {
      await reader.cancel().catch(() => void 0);
      return null;
    }
    chunks.push(value);
  }
  const all = new Uint8Array(total);
  let at = 0;
  for (const c of chunks) {
    all.set(c, at);
    at += c.byteLength;
  }
  return new TextDecoder().decode(all);
}
function apiErrors(text) {
  try {
    const body = JSON.parse(text);
    const msgs = (body.errors ?? []).map(
      (e) => `${String(e.code ?? "")} ${e.message ?? ""}`.trim()
    );
    if (msgs.length > 0) return redact(msgs.join("; ")).slice(0, 300);
  } catch {
  }
  return redact(text.slice(0, 200));
}
function errorForStatus(status, body, browserMs, retryAfterMs) {
  const detail = apiErrors(body);
  const extra = { browserMs, ...retryAfterMs === null ? {} : { retryAfterMs } };
  if (status === 429) return new RenderError("rate-limited", `HTTP 429 ${detail}`, extra);
  if (status === 401 || status === 403) {
    return new RenderError(
      "unavailable",
      `HTTP ${String(status)}: the API token was refused (${detail})`,
      extra
    );
  }
  if (status === 400)
    return new RenderError("unavailable", `HTTP 400: request refused (${detail})`, extra);
  if (status >= 500) {
    if (/time(d)? ?out|navigat|net::err/i.test(detail)) {
      return new RenderError("timeout", `HTTP ${String(status)} ${detail}`, extra);
    }
    return new RenderError("unavailable", `HTTP ${String(status)} ${detail}`, extra);
  }
  return new RenderError("navigation", `HTTP ${String(status)} ${detail}`, extra);
}
function sleep(ms, signal) {
  return new Promise((resolve, reject) => {
    if (signal?.aborted) {
      reject(new RenderError("aborted", "aborted"));
      return;
    }
    const onAbort = () => {
      clearTimeout(timer);
      reject(new RenderError("aborted", "aborted while waiting"));
    };
    const timer = setTimeout(() => {
      signal?.removeEventListener("abort", onAbort);
      resolve();
    }, ms);
    signal?.addEventListener("abort", onAbort, { once: true });
  });
}
var BrowserRenderingRenderer = class {
  o;
  fetchImpl;
  now;
  log;
  lastCallAt = Number.NEGATIVE_INFINITY;
  constructor(opts) {
    this.o = { ...DEFAULTS, ...opts };
    this.fetchImpl = opts.fetch ?? ((input, init) => fetch(input, init));
    this.now = opts.now ?? Date.now;
    this.log = opts.log ?? silentLogger;
  }
  close() {
    return Promise.resolve();
  }
  async render(req) {
    const url = snapshotUrl(this.o.apiUrl, this.o.accountId);
    const body = JSON.stringify(snapshotRequestBody(req, this.o));
    let browserMs = 0;
    for (let attempt = 0; ; attempt++) {
      const wait = this.lastCallAt + this.o.minIntervalMs - this.now();
      if (wait > 0) await sleep(wait, req.signal);
      this.lastCallAt = this.now();
      const started = this.now();
      const timeout = AbortSignal.timeout(req.timeoutMs);
      const signal = req.signal ? AbortSignal.any([req.signal, timeout]) : timeout;
      let res;
      let text;
      try {
        res = await this.fetchImpl(url, {
          method: "POST",
          headers: {
            authorization: `Bearer ${this.o.apiToken}`,
            "content-type": "application/json"
          },
          body,
          signal
        });
        text = await readLimited(res, this.o.maxResponseBytes);
      } catch (e) {
        const elapsed2 = this.now() - started;
        if (req.signal?.aborted) {
          throw new RenderError("aborted", "aborted during the REST call", {
            browserMs: browserMs + elapsed2
          });
        }
        const why = timeout.aborted ? `no answer within ${String(req.timeoutMs)} ms` : redact(e instanceof Error ? e.message : String(e));
        throw new RenderError("unavailable", `Browser Rendering: ${why}`, {
          browserMs: browserMs + elapsed2
        });
      }
      const elapsed = this.now() - started;
      const used = res.status === 429 ? 0 : browserMsHeader(res.headers) ?? elapsed;
      browserMs += used;
      if (text === null) {
        throw new RenderError(
          "screenshot",
          `the answer is over ${String(this.o.maxResponseBytes)} bytes`,
          {
            browserMs
          }
        );
      }
      if (res.status === 429) {
        const retryAfterMs = parseRetryAfter(res.headers.get("retry-after"), this.now());
        if (attempt < this.o.rateLimitRetries && retryAfterMs !== null && retryAfterMs <= this.o.maxInlineRetryAfterMs) {
          this.log.info("renderer.rate_limited_wait", { retryAfterMs });
          await sleep(retryAfterMs, req.signal);
          continue;
        }
        throw errorForStatus(429, text, browserMs, retryAfterMs);
      }
      if (res.status !== 200) {
        const err = errorForStatus(res.status, text, browserMs, null);
        if (res.status === 400 || res.status === 401 || res.status === 403) {
          this.log.error("renderer.request_refused", { status: res.status, error: err.message });
        }
        throw err;
      }
      return this.toResult(text, elapsed, browserMs);
    }
  }
  toResult(text, elapsed, browserMs) {
    let envelope;
    try {
      envelope = JSON.parse(text);
    } catch {
      throw new RenderError("unavailable", "Browser Rendering answered 200 without JSON", {
        browserMs
      });
    }
    const content = envelope.result?.content;
    const shot = envelope.result?.screenshot;
    if (envelope.success === false || typeof content !== "string" || typeof shot !== "string") {
      throw new RenderError("unavailable", `unexpected answer: ${apiErrors(text)}`, { browserMs });
    }
    const report = readCaptureReport(content);
    if (!report.page) {
      throw new RenderError(
        "shell-refused",
        "the capture page was not served (the capture gate refused the URL, or it did not load)",
        { browserMs }
      );
    }
    if (report.state === "failed") {
      throw new RenderError(
        "navigation",
        `capture page: failed ${redact(report.detail ?? "")}`.trim(),
        {
          browserMs
        }
      );
    }
    let image;
    try {
      image = base64ToBytes(shot);
    } catch {
      throw new RenderError("screenshot", "the screenshot is not base64", { browserMs });
    }
    return {
      image,
      format: "webp",
      ready: { reason: report.state === "ready" ? "signal" : "cap", afterMs: elapsed },
      durationMs: elapsed,
      paint: report.paint ?? "empty",
      browserMs,
      blocked: { navigations: 0, popups: 0 },
      notes: report.detail ? [redact(report.detail)] : []
    };
  }
};

// ../../packages/runtime/src/bundler/resolve.ts
var SHARED_EXTERNALS = ["react", "react-dom"];
var MAX_ASSET_BYTES = 200 * 1024;
var NODE_BUILTINS = new Set(
  "assert async_hooks buffer child_process cluster console constants crypto dgram diagnostics_channel dns domain events fs http http2 https inspector module net os path perf_hooks process punycode querystring readline repl stream string_decoder sys timers tls trace_events tty url util v8 vm wasi worker_threads zlib".split(
    " "
  )
);
var PINNED_VERSION_RE = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;
function isPinnedVersion(v) {
  return PINNED_VERSION_RE.test(v);
}
function trimBase(cdnBaseUrl) {
  return cdnBaseUrl.replace(/\/+$/, "");
}
function cdnModuleUrl(cdnBaseUrl, name, version, subpath, withExternals = true, deps = []) {
  const url = `${trimBase(cdnBaseUrl)}/${name}@${version}${subpath}`;
  if (!withExternals) return url;
  const query = `?external=${SHARED_EXTERNALS.join(",")}`;
  return deps.length > 0 ? `${url}${query}&deps=${deps.join(",")}` : `${url}${query}`;
}
function buildImportMap(dependencies, cdnBaseUrl) {
  const imports = {};
  const react = dependencies["react"];
  const reactDom = dependencies["react-dom"];
  if (react && isPinnedVersion(react)) {
    imports["react"] = cdnModuleUrl(cdnBaseUrl, "react", react, "", false);
    imports["react/jsx-runtime"] = cdnModuleUrl(cdnBaseUrl, "react", react, "/jsx-runtime");
    imports["react/jsx-dev-runtime"] = cdnModuleUrl(cdnBaseUrl, "react", react, "/jsx-dev-runtime");
  }
  if (reactDom && isPinnedVersion(reactDom)) {
    imports["react-dom"] = cdnModuleUrl(cdnBaseUrl, "react-dom", reactDom, "");
    imports["react-dom/client"] = cdnModuleUrl(cdnBaseUrl, "react-dom", reactDom, "/client");
  }
  return { imports };
}

// ../sandbox-shell/src/capture-sig.ts
var CAPTURE_SIG_VERSION = "br-capture-v1";
var CAPTURE_MIN_SECRET_LENGTH = 32;
var EXP_RE = /^[1-9]\d{0,11}$/;
function canonicalCaptureString(host, pathname, params) {
  const query = Object.keys(params).sort().map((k) => `${encodeURIComponent(k)}=${encodeURIComponent(params[k] ?? "")}`).join("&");
  return [CAPTURE_SIG_VERSION, host.toLowerCase(), pathname, query].join("\n");
}
function assertSecret(secret) {
  if (secret.length < CAPTURE_MIN_SECRET_LENGTH) {
    throw new Error(
      `capture HMAC secret must be at least ${String(CAPTURE_MIN_SECRET_LENGTH)} characters`
    );
  }
}
async function hmacKey(secret, usage) {
  return crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    [usage]
  );
}
function toBase64Url(bytes) {
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
function isHttpUrl(s) {
  try {
    const u = new URL(s);
    return u.protocol === "https:" || u.protocol === "http:";
  } catch {
    return false;
  }
}
async function signCaptureParams(secret, host, pathname, params) {
  assertSecret(secret);
  const key = await hmacKey(secret, "sign");
  const mac = await crypto.subtle.sign(
    "HMAC",
    key,
    new TextEncoder().encode(canonicalCaptureString(host, pathname, params))
  );
  return toBase64Url(new Uint8Array(mac));
}
async function signCaptureUrl(input) {
  const url = new URL(input.captureUrl);
  if (url.search || url.hash) throw new Error("captureUrl must not have a query or fragment");
  if (!Number.isInteger(input.exp) || !EXP_RE.test(String(input.exp))) {
    throw new Error("exp must be a positive integer (unix seconds)");
  }
  if (!isHttpUrl(input.src)) throw new Error("src must be an http(s) URL");
  if (input.css !== void 0 && !isHttpUrl(input.css))
    throw new Error("css must be an http(s) URL");
  const params = { src: input.src, exp: String(input.exp) };
  if (input.css !== void 0) params["css"] = input.css;
  if (input.map !== void 0) params["map"] = input.map;
  const sig = await signCaptureParams(input.secret, url.host, url.pathname, params);
  const query = Object.keys(params).sort().map((k) => `${encodeURIComponent(k)}=${encodeURIComponent(params[k] ?? "")}`);
  query.push(`sig=${sig}`);
  url.search = `?${query.join("&")}`;
  return url.toString();
}

// src/backend.ts
var JOB_LEASE_MS = 12e4;
var BUCKET_EPHEMERAL = "ephemeral-builds";
var BUCKET_SCREENSHOTS = "screenshots";
var BackendError = class extends Error {
  constructor(message, status, code) {
    super(message);
    this.status = status;
    this.code = code;
    this.name = "BackendError";
  }
  status;
  code;
};
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
function isUuid(s) {
  return UUID_RE.test(s);
}

// src/capture-policy.ts
var SERVICE_FALLBACK_ATTEMPT = 3;
function classifyRenderFailure(e) {
  if (e instanceof RenderError && (e.code === "rate-limited" || e.code === "unavailable")) {
    return "service";
  }
  return "render";
}
function afterNoRender(kind, attempts) {
  if (kind === "service" && attempts < SERVICE_FALLBACK_ATTEMPT) return "retry";
  return "fallback";
}

// src/paths.ts
function assertUuid(what, id) {
  if (!isUuid(id)) throw new Error(`${what} is not a canonical UUID`);
}
function buildSources(build) {
  assertUuid("battle_id", build.battle_id);
  assertUuid("builder_id", build.builder_id);
  const base = `${build.battle_id}/${build.builder_id}/`;
  if (build.status === "shipped") {
    return {
      kind: "shipped",
      js: `${base}bundle.js`,
      css: `${base}bundle.css`,
      source: `${base}source.json`,
      thumb: `${base}thumb.webp`
    };
  }
  if (build.status === "auto_shipped") {
    return {
      kind: "autosave",
      js: `${base}autosave/bundle.js`,
      css: `${base}autosave/bundle.css`,
      source: `${base}autosave/source.json`,
      thumb: `${base}thumb.webp`
    };
  }
  throw new Error(`a ${build.status} build has nothing to capture`);
}
function screenshotPath(build) {
  assertUuid("battle_id", build.battle_id);
  assertUuid("build id", build.id);
  return `${build.battle_id}/${build.id}.webp`;
}
function screenshotPrefix(battleId) {
  assertUuid("battle id", battleId);
  return `${battleId}/`;
}
function isScreenshotOf(buildId, name) {
  assertUuid("build id", buildId);
  return name.startsWith(`${buildId}.`) && !name.includes("/");
}
function battlePrefix(battleId) {
  assertUuid("battle id", battleId);
  return `${battleId}/`;
}

// src/capture-job.ts
var MAX_SOURCE_BYTES = 5 * 1024 * 1024;
function captureUrlFor(config, buildId) {
  return config.shellCaptureUrl.replaceAll("{build}", buildId);
}
async function importMapFor(backend, sourcePath, cdnUrl, log) {
  try {
    const bytes = await backend.download(BUCKET_EPHEMERAL, sourcePath);
    if (!bytes) {
      log.warn("capture.no_source_json");
      return { imports: {} };
    }
    if (bytes.byteLength > MAX_SOURCE_BYTES) throw new Error("source.json is too large");
    const parsed = JSON.parse(new TextDecoder().decode(bytes));
    const deps = parsed.manifest?.dependencies;
    if (typeof deps !== "object" || deps === null || Array.isArray(deps)) {
      throw new Error("source.json has no manifest.dependencies object");
    }
    const strings = {};
    for (const [k, v] of Object.entries(deps)) if (typeof v === "string") strings[k] = v;
    return buildImportMap(strings, cdnUrl);
  } catch (e) {
    log.warn("capture.bad_manifest", { error: errorMessage(e) });
    return { imports: {} };
  }
}
async function renderWithBudget(deps, url, signal) {
  const { budget, config } = deps;
  const req = { url, viewport: config.viewport, timeoutMs: config.captureTimeoutMs, signal };
  if (!budget) return { result: await deps.renderer.render(req) };
  let ticket;
  try {
    ticket = await budget.reserve();
  } catch (e) {
    throw new RenderError("unavailable", `browser budget: ${errorMessage(e)}`);
  }
  if (!ticket) return { spent: true };
  let browserMs = 0;
  let rateLimited = false;
  try {
    const result = await deps.renderer.render(req);
    browserMs = result.browserMs ?? result.durationMs;
    return { result };
  } catch (e) {
    if (e instanceof RenderError) {
      browserMs = e.extra.browserMs ?? 0;
      rateLimited = e.code === "rate-limited";
    }
    throw e;
  } finally {
    await budget.settle(ticket, { browserMs, rateLimited });
  }
}
async function renderBuild(deps, build, sources, signal, log) {
  const { backend, config } = deps;
  const ttl = config.signedUrlTtlSeconds;
  const src = await backend.createSignedUrl(BUCKET_EPHEMERAL, sources.js, ttl);
  if (!src) return { kind: "missing" };
  const css = await backend.createSignedUrl(BUCKET_EPHEMERAL, sources.css, ttl);
  const map = await importMapFor(backend, sources.source, config.pkgCdnUrl, log);
  const now = deps.now ?? Date.now;
  const url = await signCaptureUrl({
    captureUrl: captureUrlFor(config, build.id),
    src,
    css: css ?? void 0,
    map: JSON.stringify(map),
    exp: Math.floor(now() / 1e3) + ttl,
    secret: config.hmacSecret
  });
  const rendered = await renderWithBudget(deps, url, signal);
  if ("spent" in rendered) {
    return {
      kind: "no-render",
      why: "budget",
      reason: "today's browser rendering budget is spent"
    };
  }
  const result = rendered.result;
  log.info("capture.rendered", {
    ready: result.ready.reason,
    readyAfterMs: result.ready.afterMs,
    renderMs: result.durationMs,
    ...result.browserMs === void 0 ? {} : { browserMs: result.browserMs },
    ...result.paint === void 0 ? {} : { paint: result.paint },
    blocked: result.blocked,
    notes: result.notes
  });
  const check = await deps.imaging.screenshot(result, config.viewport);
  if (!check.ok) return { kind: "no-render", why: "render", reason: check.reason };
  return { kind: "ok", webp: check.webp, ready: result.ready.reason, renderMs: result.durationMs };
}
async function giveUpOrRetry(deps, job, reason, log) {
  try {
    const after = await deps.backend.failJob(job.id, reason);
    if (after.status === "failed") {
      log.warn("capture.gave_up", { reason, attempts: after.attempts });
      return { result: "failed", reason };
    }
    log.info("capture.retry", { reason, attempts: after.attempts, runAfter: after.run_after });
    return { result: "retry", reason, attempts: after.attempts };
  } catch (e) {
    log.error("capture.fail_job_failed", { reason, error: errorMessage(e) });
    return { result: "error", reason: `${reason}; fail_job: ${errorMessage(e)}` };
  }
}
async function processCaptureJob(deps, job, signal) {
  const log = deps.log.child({
    job: job.id,
    kind: "capture",
    build: job.ref_id,
    attempt: job.attempts
  });
  try {
    return await runCapture(deps, job, signal, log);
  } catch (e) {
    const reason = signal.aborted ? `aborted: ${errorMessage(signal.reason)}` : `unexpected: ${errorMessage(e)}`;
    log.error("capture.error", { reason });
    return giveUpOrRetry(deps, job, reason, log);
  }
}
async function runCapture(deps, job, signal, log) {
  const { backend, config } = deps;
  if (!isUuid(job.ref_id)) return giveUpOrRetry(deps, job, "job ref_id is not a build id", log);
  const build = await backend.getBuild(job.ref_id);
  if (!build) return giveUpOrRetry(deps, job, "build not found", log);
  let sources;
  let target;
  try {
    sources = buildSources(build);
    target = screenshotPath(build);
  } catch (e) {
    return giveUpOrRetry(deps, job, errorMessage(e), log);
  }
  let attempt;
  try {
    attempt = await renderBuild(deps, build, sources, signal, log);
  } catch (e) {
    if (signal.aborted || e instanceof RenderError && e.code === "aborted") throw e;
    attempt = { kind: "no-render", why: classifyRenderFailure(e), reason: errorMessage(e) };
  }
  if (attempt.kind === "ok") {
    await backend.upload(BUCKET_SCREENSHOTS, target, attempt.webp, "image/webp");
    await backend.completeCapture(build.id, "captured", target);
    log.info("capture.captured", {
      path: target,
      bytes: attempt.webp.byteLength,
      ready: attempt.ready
    });
    return { result: "captured", path: target, ready: attempt.ready, renderMs: attempt.renderMs };
  }
  const renderFailure = attempt.kind === "missing" ? `${sources.kind} bundle.js is missing` : attempt.reason;
  if (attempt.kind === "no-render" && afterNoRender(attempt.why, job.attempts) === "retry") {
    log.warn("capture.service_failed", { reason: renderFailure });
    return giveUpOrRetry(deps, job, renderFailure, log);
  }
  if (attempt.kind === "no-render" && attempt.why === "budget") {
    log.info("capture.budget_spent", { reason: renderFailure });
  } else {
    log.warn("capture.render_unusable", { reason: renderFailure });
  }
  const thumb = await backend.download(BUCKET_EPHEMERAL, sources.thumb);
  let thumbProblem = "no client thumbnail";
  if (thumb) {
    let webp = null;
    try {
      webp = await deps.imaging.thumbnail(thumb, config.viewport);
    } catch (e) {
      thumbProblem = `the client thumbnail is not a usable image (${errorMessage(e)})`;
    }
    if (webp) {
      await backend.upload(BUCKET_SCREENSHOTS, target, webp, "image/webp");
      await backend.completeCapture(build.id, "fallback", target);
      log.info("capture.fallback", { path: target, bytes: webp.byteLength, reason: renderFailure });
      return { result: "fallback", path: target, reason: renderFailure };
    }
  }
  const reason = `${renderFailure}; ${thumbProblem}`;
  if (attempt.kind === "missing" && !thumb) {
    await backend.completeCapture(build.id, "failed", null);
    log.warn("capture.failed", { reason });
    return { result: "failed", reason };
  }
  return giveUpOrRetry(deps, job, reason, log);
}

// src/destroy-job.ts
var DELETE_BATCH = 100;
var MAX_DEPTH = 4;
var MAX_OBJECTS = 1e4;
async function listRecursive(backend, bucket, prefix, depth = 0, out = []) {
  if (depth > MAX_DEPTH)
    throw new Error(`folder nesting deeper than ${String(MAX_DEPTH)} under ${prefix}`);
  for (const entry of await backend.list(bucket, prefix)) {
    if (!entry.name || entry.name.includes("/") || entry.name === "." || entry.name === "..") {
      throw new Error(`unexpected entry name ${JSON.stringify(entry.name)} under ${prefix}`);
    }
    if (entry.isFolder) {
      await listRecursive(backend, bucket, `${prefix}${entry.name}/`, depth + 1, out);
    } else {
      out.push(`${prefix}${entry.name}`);
    }
    if (out.length > MAX_OBJECTS)
      throw new Error(`more than ${String(MAX_OBJECTS)} objects under ${prefix}`);
  }
  return out;
}
async function giveUpOrRetry2(backend, job, reason, log) {
  try {
    const after = await backend.failJob(job.id, reason);
    if (after.status === "failed") {
      log.warn("destroy.gave_up", { reason, attempts: after.attempts });
      return { result: "failed", reason };
    }
    log.info("destroy.retry", { reason, attempts: after.attempts, runAfter: after.run_after });
    return { result: "retry", reason, attempts: after.attempts };
  } catch (e) {
    log.error("destroy.fail_job_failed", { reason, error: errorMessage(e) });
    return { result: "error", reason: `${reason}; fail_job: ${errorMessage(e)}` };
  }
}
async function processDestroyJob(deps, job, signal) {
  const { backend } = deps;
  const log = deps.log.child({
    job: job.id,
    kind: "destroy",
    battle: job.ref_id,
    attempt: job.attempts
  });
  try {
    const prefix = battlePrefix(job.ref_id);
    const phase = await backend.getBattlePhase(job.ref_id);
    if (phase !== "destroyed" && phase !== "abandoned") {
      return await giveUpOrRetry2(
        backend,
        job,
        `battle is ${phase ?? "missing"}, not destroyed`,
        log
      );
    }
    const names = await listRecursive(backend, BUCKET_EPHEMERAL, prefix);
    let deleted = 0;
    for (let i = 0; i < names.length; i += DELETE_BATCH) {
      signal.throwIfAborted();
      deleted += (await backend.remove(BUCKET_EPHEMERAL, names.slice(i, i + DELETE_BATCH))).length;
    }
    const left = await listRecursive(backend, BUCKET_EPHEMERAL, prefix);
    if (left.length > 0) {
      return await giveUpOrRetry2(
        backend,
        job,
        `${String(left.length)} objects left after delete`,
        log
      );
    }
    signal.throwIfAborted();
    await backend.completeDestroy(job.ref_id);
    log.info("destroy.done", { listed: names.length, deleted });
    return { result: "destroyed", deleted };
  } catch (e) {
    const reason = signal.aborted ? `aborted: ${errorMessage(signal.reason)}` : `unexpected: ${errorMessage(e)}`;
    log.error("destroy.error", { reason });
    return giveUpOrRetry2(backend, job, reason, log);
  }
}

// src/takedown-job.ts
async function giveUpOrRetry3(backend, job, reason, log) {
  try {
    const after = await backend.failJob(job.id, reason);
    if (after.status === "failed") {
      log.warn("takedown.gave_up", { reason, attempts: after.attempts });
      return { result: "failed", reason };
    }
    log.info("takedown.retry", { reason, attempts: after.attempts, runAfter: after.run_after });
    return { result: "retry", reason, attempts: after.attempts };
  } catch (e) {
    log.error("takedown.fail_job_failed", { reason, error: errorMessage(e) });
    return { result: "error", reason: `${reason}; fail_job: ${errorMessage(e)}` };
  }
}
async function screenshotsOf(backend, battleId, buildId) {
  const prefix = screenshotPrefix(battleId);
  return (await backend.list(BUCKET_SCREENSHOTS, prefix)).filter((e) => !e.isFolder && isScreenshotOf(buildId, e.name)).map((e) => `${prefix}${e.name}`);
}
async function processTakedownJob(deps, job, signal) {
  const { backend } = deps;
  const log = deps.log.child({
    job: job.id,
    kind: "takedown",
    build: job.ref_id,
    attempt: job.attempts
  });
  try {
    const build = await backend.getBuild(job.ref_id);
    if (!build) return await giveUpOrRetry3(backend, job, "build is missing", log);
    if (!build.taken_down_at) {
      return await giveUpOrRetry3(backend, job, "build is not taken down", log);
    }
    const names = await screenshotsOf(backend, build.battle_id, build.id);
    signal.throwIfAborted();
    const deleted = (await backend.remove(BUCKET_SCREENSHOTS, names)).length;
    const left = await screenshotsOf(backend, build.battle_id, build.id);
    if (left.length > 0) {
      return await giveUpOrRetry3(
        backend,
        job,
        `${String(left.length)} screenshots left after delete`,
        log
      );
    }
    signal.throwIfAborted();
    await backend.completeTakedown(build.id);
    log.info("takedown.done", { listed: names.length, deleted });
    return { result: "taken_down", deleted };
  } catch (e) {
    const reason = signal.aborted ? `aborted: ${errorMessage(signal.reason)}` : `unexpected: ${errorMessage(e)}`;
    log.error("takedown.error", { reason });
    return giveUpOrRetry3(backend, job, reason, log);
  }
}

// src/runner.ts
var DEFAULT_RUNNER_OPTIONS = {
  captureConcurrency: 1,
  idleMinMs: 1e3,
  idleMaxMs: 15e3,
  jobTimeoutMs: 9e4,
  shutdownGraceMs: 3e4
};
var WorkerRunner = class {
  constructor(deps, opts = {}) {
    this.deps = deps;
    this.opts = { ...DEFAULT_RUNNER_OPTIONS, ...opts };
    if (this.opts.captureConcurrency < 1) throw new Error("captureConcurrency must be >= 1");
  }
  deps;
  opts;
  stopping = false;
  stopCtrl = new AbortController();
  loops = [];
  inflight = /* @__PURE__ */ new Set();
  /** Starts the polling loops. */
  start() {
    if (this.loops.length > 0) throw new Error("already started");
    const kinds = this.opts.kinds ?? ["capture", "destroy", "takedown"];
    if (kinds.includes("capture")) {
      for (let i = 0; i < this.opts.captureConcurrency; i++) {
        this.loops.push(this.loop("capture", i));
      }
    }
    if (kinds.includes("destroy")) this.loops.push(this.loop("destroy", 0));
    if (kinds.includes("takedown")) this.loops.push(this.loop("takedown", 0));
  }
  /**
   * Stops claiming, waits up to `shutdownGraceMs` for the jobs in flight, then aborts them
   * (they record the abort with `fail_job`) and waits for the loops to end.
   */
  async stop() {
    if (!this.stopping) {
      this.stopping = true;
      this.stopCtrl.abort();
      this.deps.log.info("worker.stopping", { inflight: this.inflight.size });
    }
    const all = Promise.all(this.loops);
    let graceTimer;
    const finished = await Promise.race([
      all.then(() => true),
      new Promise((resolve) => {
        graceTimer = setTimeout(() => {
          resolve(false);
        }, this.opts.shutdownGraceMs);
      })
    ]);
    clearTimeout(graceTimer);
    if (!finished) {
      this.deps.log.warn("worker.abandoning", { jobs: [...this.inflight].map((f) => f.job.id) });
      for (const f of this.inflight) f.ctrl.abort(new Error("worker shutting down"));
      await all;
    }
    this.deps.log.info("worker.stopped");
  }
  /**
   * Aborts every job in flight now; each records the abort with `fail_job` and is retried
   * after its backoff. The `jobs` Edge Function calls this before its wall-clock limit.
   */
  abortInflight(reason) {
    for (const f of this.inflight) f.ctrl.abort(new Error(reason));
  }
  /**
   * Processes jobs of one kind until the queue has none ready (or `max` were processed).
   * For `--once` runs and tests; independent of `start()`.
   */
  async drain(kind, max = 100) {
    const out = [];
    while (out.length < max && !this.stopping) {
      const job = await this.deps.backend.claimJob(kind);
      if (!job) break;
      out.push({ job, outcome: await this.runJob(job) });
    }
    return out;
  }
  /** Runs one claimed job with its own timeout. Never throws. */
  async runJob(job) {
    const ctrl = new AbortController();
    const entry = { job, ctrl };
    const timer = setTimeout(() => {
      ctrl.abort(new Error(`job timeout after ${String(this.opts.jobTimeoutMs)} ms`));
    }, this.opts.jobTimeoutMs);
    this.inflight.add(entry);
    const started = Date.now();
    const log = this.deps.log.child({ job: job.id, kind: job.kind, ref: job.ref_id });
    log.info("job.start", { attempt: job.attempts });
    try {
      const outcome = job.kind === "capture" ? await processCaptureJob(
        {
          backend: this.deps.backend,
          renderer: this.deps.renderer,
          imaging: this.deps.imaging,
          budget: this.deps.budget,
          config: this.deps.capture,
          log: this.deps.log
        },
        job,
        ctrl.signal
      ) : job.kind === "destroy" ? await processDestroyJob(
        { backend: this.deps.backend, log: this.deps.log },
        job,
        ctrl.signal
      ) : await processTakedownJob(
        { backend: this.deps.backend, log: this.deps.log },
        job,
        ctrl.signal
      );
      log.info("job.end", { result: outcome.result, ms: Date.now() - started });
      return outcome;
    } catch (e) {
      log.error("job.crashed", { error: errorMessage(e) });
      return { result: "error", reason: errorMessage(e) };
    } finally {
      clearTimeout(timer);
      this.inflight.delete(entry);
    }
  }
  async loop(kind, index) {
    const log = this.deps.log.child({ loop: `${kind}#${String(index)}` });
    let idle = this.opts.idleMinMs;
    while (!this.stopping) {
      let job;
      try {
        job = await this.deps.backend.claimJob(kind);
      } catch (e) {
        log.error("claim.failed", { error: errorMessage(e), retryInMs: idle });
        await this.pause(idle);
        idle = Math.min(idle * 2, this.opts.idleMaxMs);
        continue;
      }
      if (!job) {
        await this.pause(idle);
        idle = Math.min(idle * 2, this.opts.idleMaxMs);
        continue;
      }
      idle = this.opts.idleMinMs;
      await this.runJob(job);
    }
  }
  /** Sleeps `ms`, or less when `stop()` is called. */
  pause(ms) {
    if (this.stopCtrl.signal.aborted) return Promise.resolve();
    return new Promise((resolve) => {
      const done = () => {
        clearTimeout(timer);
        this.stopCtrl.signal.removeEventListener("abort", done);
        resolve();
      };
      const timer = setTimeout(done, ms);
      this.stopCtrl.signal.addEventListener("abort", done, { once: true });
    });
  }
};

// src/supabase.ts
var LIST_PAGE = 1e3;
var SupabaseBackend = class {
  base;
  publicBase;
  headers;
  timeoutMs;
  fetchImpl;
  constructor(opts) {
    this.base = opts.url.replace(/\/+$/, "");
    this.publicBase = (opts.publicUrl ?? opts.url).replace(/\/+$/, "");
    this.headers = {
      apikey: opts.serviceKey,
      ...opts.serviceKey.startsWith("eyJ") ? { authorization: `Bearer ${opts.serviceKey}` } : {}
    };
    this.timeoutMs = opts.timeoutMs ?? 15e3;
    this.fetchImpl = opts.fetch ?? fetch;
  }
  // ─── RPCs and tables ────────────────────────────────────────────────────
  async claimJob(kind) {
    const row = await this.rpc("claim_job", { p_kind: kind });
    const id = row?.id ?? null;
    if (row === null || id === null) return null;
    return { ...row, id };
  }
  async completeCapture(buildId, status, path) {
    await this.rpc("complete_capture", { p_build_id: buildId, p_status: status, p_path: path });
  }
  async failJob(jobId, error) {
    return await this.rpc("fail_job", { p_job_id: jobId, p_error: error.slice(0, 2e3) });
  }
  async completeDestroy(battleId) {
    await this.rpc("complete_destroy", { p_battle_id: battleId });
  }
  async completeTakedown(buildId) {
    await this.rpc("complete_takedown", { p_build_id: buildId });
  }
  async getBuild(buildId) {
    const q = new URLSearchParams({
      id: `eq.${buildId}`,
      select: "id,battle_id,builder_id,status,capture_status,taken_down_at"
    });
    const res = await this.request("GET", `/rest/v1/builds?${q.toString()}`);
    const rows = await this.json(res);
    return rows[0] ?? null;
  }
  async getBattlePhase(battleId) {
    const q = new URLSearchParams({ id: `eq.${battleId}`, select: "phase" });
    const res = await this.request("GET", `/rest/v1/battles?${q.toString()}`);
    const rows = await this.json(res);
    return rows[0]?.phase ?? null;
  }
  // ─── Browser Rendering budget (T-034) ───────────────────────────────────
  async reserveBrowserTime(reserveMs, limitMs) {
    const row = await this.rpc("browser_budget_reserve", {
      p_reserve_ms: reserveMs,
      p_limit_ms: limitMs
    });
    return {
      granted: row.granted,
      day: row.day,
      usedMs: row.used_ms,
      reservedMs: row.reserved_ms,
      limitMs: row.limit_ms
    };
  }
  async settleBrowserTime(day, reservedMs, usedMs, rateLimited) {
    await this.rpc("browser_budget_settle", {
      p_day: day,
      p_reserved_ms: reservedMs,
      p_used_ms: usedMs,
      p_rate_limited: rateLimited
    });
  }
  // ─── Storage ────────────────────────────────────────────────────────────
  async createSignedUrl(bucket, path, expiresInSeconds) {
    const res = await this.request(
      "POST",
      `/storage/v1/object/sign/${bucket}/${encodePath(path)}`,
      {
        json: { expiresIn: expiresInSeconds },
        allowNotFound: true
      }
    );
    if (res === null) return null;
    const body = await this.json(res);
    if (!body.signedURL)
      throw new BackendError("sign: no signedURL in the response", 500, void 0);
    return `${this.publicBase}/storage/v1${body.signedURL}`;
  }
  async download(bucket, path) {
    const res = await this.request(
      "GET",
      `/storage/v1/object/authenticated/${bucket}/${encodePath(path)}`,
      { allowNotFound: true }
    );
    if (res === null) return null;
    return new Uint8Array(await res.arrayBuffer());
  }
  async upload(bucket, path, body, contentType) {
    const res = await this.request("POST", `/storage/v1/object/${bucket}/${encodePath(path)}`, {
      body,
      headers: { "content-type": contentType, "x-upsert": "true", "cache-control": "max-age=300" }
    });
    await res.arrayBuffer();
  }
  async list(bucket, prefix) {
    const out = [];
    for (let offset = 0; ; offset += LIST_PAGE) {
      const res = await this.request("POST", `/storage/v1/object/list/${bucket}`, {
        json: { prefix, limit: LIST_PAGE, offset, sortBy: { column: "name", order: "asc" } }
      });
      const page = await this.json(res);
      for (const e of page) out.push({ name: e.name, isFolder: e.id === null });
      if (page.length < LIST_PAGE) return out;
    }
  }
  async remove(bucket, paths) {
    if (paths.length === 0) return [];
    const res = await this.request("DELETE", `/storage/v1/object/${bucket}`, {
      json: { prefixes: paths }
    });
    const rows = await this.json(res);
    return rows.map((r) => r.name);
  }
  // ─── HTTP ───────────────────────────────────────────────────────────────
  async rpc(fn, args) {
    const res = await this.request("POST", `/rest/v1/rpc/${fn}`, { json: args });
    return this.json(res);
  }
  async json(res) {
    const text = await res.text();
    return text ? JSON.parse(text) : null;
  }
  async request(method, path, opts = {}) {
    const headers = { ...this.headers, ...opts.headers };
    let body;
    if (opts.json !== void 0) {
      headers["content-type"] = "application/json";
      body = JSON.stringify(opts.json);
    } else if (opts.body) {
      body = new Uint8Array(opts.body);
    }
    const res = await this.fetchImpl(`${this.base}${path}`, {
      method,
      headers,
      ...body === void 0 ? {} : { body },
      signal: AbortSignal.timeout(this.timeoutMs)
    });
    if (res.ok) return res;
    const text = await res.text().catch(() => "");
    let parsed = {};
    try {
      parsed = JSON.parse(text);
    } catch {
    }
    const status = parsed.statusCode ? Number(parsed.statusCode) : res.status;
    if (status === 404 && opts.allowNotFound) return null;
    const label = `${method} ${path.split("?")[0] ?? path}`;
    throw new BackendError(
      `${label}: HTTP ${String(status)} ${parsed.message ?? text.slice(0, 200)}${parsed.details ? ` (${parsed.details})` : ""}`,
      status,
      parsed.message
    );
  }
};
function encodePath(path) {
  return path.split("/").map(encodeURIComponent).join("/");
}

// src/edge/config.ts
var FUNCTION_VIEWPORT = { width: 1280, height: 800 };
var CRON_SECRET_MIN_LENGTH = 32;
var JOB_EXTRA_MS = 27e3;
var FunctionConfigError = class extends Error {
  constructor(problems) {
    super(`invalid configuration: ${problems.join("; ")}`);
    this.problems = problems;
    this.name = "FunctionConfigError";
  }
  problems;
};
var OPTIONAL = {
  BROWSER_RENDERING_API_URL,
  BROWSER_RENDERING_MIN_INTERVAL_MS: FREE_PLAN_MIN_INTERVAL_MS,
  BROWSER_BUDGET_MS_PER_DAY: DEFAULT_BROWSER_BUDGET_MS,
  BROWSER_RESERVE_MS: DEFAULT_BROWSER_RESERVE_MS,
  CAPTURE_TIMEOUT_MS: 35e3,
  CAPTURE_SIGNED_URL_TTL_S: 120,
  JOBS_RUN_WINDOW_MS: 5e4,
  JOBS_RUN_HARD_STOP_MS: 14e4
};
function loadFunctionConfig(env) {
  const problems = [];
  const get = (name) => {
    const v = env[name]?.trim();
    return v === void 0 || v === "" ? void 0 : v;
  };
  const str = (name) => {
    const v = get(name);
    if (v === void 0) problems.push(`${name} is required`);
    return v ?? "";
  };
  const url = (name, value) => {
    if (!value) return value;
    try {
      const u = new URL(value.replaceAll("{build}", "build"));
      if (u.protocol !== "https:" && u.protocol !== "http:") throw new Error("not http(s)");
    } catch {
      problems.push(`${name} must be an http(s) URL`);
    }
    return value.replace(/\/+$/, "");
  };
  const int = (name, fallback, min, max) => {
    const raw = get(name);
    if (raw === void 0) return fallback;
    const n = Number(raw);
    if (!Number.isInteger(n) || n < min || n > max) {
      problems.push(`${name} must be an integer between ${String(min)} and ${String(max)}`);
      return fallback;
    }
    return n;
  };
  const supabaseUrl = url("SUPABASE_URL", str("SUPABASE_URL"));
  const publicSupabaseUrl = url(
    "JOBS_PUBLIC_SUPABASE_URL",
    get("JOBS_PUBLIC_SUPABASE_URL") ?? supabaseUrl
  );
  const serviceKey = str("SUPABASE_SERVICE_ROLE_KEY");
  const cronSecret = str("JOBS_CRON_SECRET");
  if (cronSecret && cronSecret.length < CRON_SECRET_MIN_LENGTH) {
    problems.push(`JOBS_CRON_SECRET must be at least ${String(CRON_SECRET_MIN_LENGTH)} characters`);
  }
  const shellCaptureUrl = url("CAPTURE_SHELL_URL", str("CAPTURE_SHELL_URL"));
  if (shellCaptureUrl && URL.canParse(shellCaptureUrl.replaceAll("{build}", "b"))) {
    const u = new URL(shellCaptureUrl.replaceAll("{build}", "b"));
    if (!u.pathname.endsWith("/capture") || u.search || u.hash) {
      problems.push("CAPTURE_SHELL_URL must be the capture page URL (…/v1/capture, no query)");
    }
  }
  const hmacSecret = str("CAPTURE_HMAC_SECRET");
  if (hmacSecret && hmacSecret.length < CAPTURE_MIN_SECRET_LENGTH) {
    problems.push(
      `CAPTURE_HMAC_SECRET must be at least ${String(CAPTURE_MIN_SECRET_LENGTH)} characters`
    );
  }
  const pkgCdnUrl = url("PKG_CDN_URL", str("PKG_CDN_URL"));
  const accountId = str("BROWSER_RENDERING_ACCOUNT_ID");
  if (accountId && !/^[0-9A-Za-z_-]{1,64}$/.test(accountId)) {
    problems.push("BROWSER_RENDERING_ACCOUNT_ID is not an account id");
  }
  const apiToken = str("BROWSER_RENDERING_API_TOKEN");
  const apiUrl = url(
    "BROWSER_RENDERING_API_URL",
    get("BROWSER_RENDERING_API_URL") ?? OPTIONAL.BROWSER_RENDERING_API_URL
  );
  const level = get("LOG_LEVEL") ?? "info";
  if (!isLogLevel(level)) problems.push("LOG_LEVEL must be debug, info, warn or error");
  const captureTimeoutMs = int("CAPTURE_TIMEOUT_MS", OPTIONAL.CAPTURE_TIMEOUT_MS, 1e4, 6e4);
  const minIntervalMs = int(
    "BROWSER_RENDERING_MIN_INTERVAL_MS",
    OPTIONAL.BROWSER_RENDERING_MIN_INTERVAL_MS,
    0,
    6e4
  );
  const jobTimeoutMs = captureTimeoutMs + minIntervalMs + JOB_EXTRA_MS;
  if (jobTimeoutMs > JOB_LEASE_MS - 1e4) {
    problems.push(
      `CAPTURE_TIMEOUT_MS + BROWSER_RENDERING_MIN_INTERVAL_MS must be at most ${String(JOB_LEASE_MS - 1e4 - JOB_EXTRA_MS)} (the job must end inside its 2-minute lease)`
    );
  }
  const windowMs = int("JOBS_RUN_WINDOW_MS", OPTIONAL.JOBS_RUN_WINDOW_MS, 1e3, 3e5);
  const hardStopMs = int("JOBS_RUN_HARD_STOP_MS", OPTIONAL.JOBS_RUN_HARD_STOP_MS, 5e3, 39e4);
  if (hardStopMs < windowMs) problems.push("JOBS_RUN_HARD_STOP_MS must be >= JOBS_RUN_WINDOW_MS");
  const signedUrlTtlSeconds = int(
    "CAPTURE_SIGNED_URL_TTL_S",
    OPTIONAL.CAPTURE_SIGNED_URL_TTL_S,
    30,
    600
  );
  const budget = {
    limitMs: int("BROWSER_BUDGET_MS_PER_DAY", OPTIONAL.BROWSER_BUDGET_MS_PER_DAY, 0, 864e5),
    reserveMs: int("BROWSER_RESERVE_MS", OPTIONAL.BROWSER_RESERVE_MS, 1e3, 12e4)
  };
  if (problems.length > 0) throw new FunctionConfigError(problems);
  return {
    supabaseUrl,
    publicSupabaseUrl,
    serviceKey,
    cronSecret,
    capture: {
      shellCaptureUrl,
      hmacSecret,
      pkgCdnUrl,
      signedUrlTtlSeconds,
      captureTimeoutMs,
      viewport: { ...FUNCTION_VIEWPORT }
    },
    browserRendering: { apiUrl, accountId, apiToken, minIntervalMs },
    budget,
    run: { windowMs, hardStopMs, jobTimeoutMs },
    logLevel: level
  };
}
function describeFunctionConfig(c) {
  return {
    supabaseUrl: c.supabaseUrl,
    publicSupabaseUrl: c.publicSupabaseUrl,
    shellCaptureUrl: c.capture.shellCaptureUrl,
    pkgCdnUrl: c.capture.pkgCdnUrl,
    browserRendering: c.browserRendering.apiUrl,
    minIntervalMs: c.browserRendering.minIntervalMs,
    budgetMsPerDay: c.budget.limitMs,
    freeBrowserMsPerDay: FREE_BROWSER_MS_PER_DAY,
    captureTimeoutMs: c.capture.captureTimeoutMs,
    ...c.run
  };
}

// src/edge/run.ts
var RUN_KINDS = ["capture", "destroy", "takedown"];
async function runJobs(deps, opts) {
  const now = deps.now ?? Date.now;
  const started = now();
  const kinds = opts.kinds ?? RUN_KINDS;
  const jobs = [];
  const state = { hardStopped: false };
  const hardStop = setTimeout(() => {
    state.hardStopped = true;
    deps.log.warn("run.hard_stop", { afterMs: now() - started });
    deps.runner.abortInflight("the function run reached its time limit");
  }, opts.hardStopMs);
  const record = (job, outcome) => {
    jobs.push({
      id: job.id,
      kind: job.kind,
      ref: job.ref_id,
      attempt: job.attempts,
      result: outcome.result
    });
  };
  let stoppedBy = "empty";
  try {
    rounds: for (; ; ) {
      let claimed = 0;
      for (const kind of kinds) {
        if (now() - started >= opts.windowMs || state.hardStopped) {
          stoppedBy = "window";
          break rounds;
        }
        let job;
        try {
          job = await deps.backend.claimJob(kind);
        } catch (e) {
          deps.log.error("claim.failed", { kind, error: errorMessage(e) });
          stoppedBy = "claim-error";
          break rounds;
        }
        if (!job) continue;
        claimed++;
        record(job, await deps.runner.runJob(job));
      }
      if (claimed === 0) break;
    }
  } finally {
    clearTimeout(hardStop);
  }
  return { ms: now() - started, stoppedBy, hardStopped: state.hardStopped, jobs };
}

// src/edge/handler.ts
var CRON_SECRET_HEADER = "x-br-cron-secret";
function sameSecret(a, b) {
  const x = new TextEncoder().encode(a);
  const y = new TextEncoder().encode(b);
  let diff = x.length ^ y.length;
  const n = Math.max(x.length, y.length);
  for (let i = 0; i < n; i++) diff |= (x[i] ?? 0) ^ (y[i] ?? 0);
  return diff === 0;
}
function json(status, body) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", "cache-control": "no-store" }
  });
}
function runId() {
  return crypto.randomUUID().slice(0, 8);
}
async function executeRun(config, log, fetchImpl) {
  const backend = new SupabaseBackend({
    url: config.supabaseUrl,
    publicUrl: config.publicSupabaseUrl,
    serviceKey: config.serviceKey,
    ...fetchImpl ? { fetch: fetchImpl } : {}
  });
  const renderer = new BrowserRenderingRenderer({
    ...config.browserRendering,
    log,
    ...fetchImpl ? { fetch: fetchImpl } : {}
  });
  const budget = new DailyBrowserBudget(backend, config.budget, log);
  const runner = new WorkerRunner(
    { backend, renderer, imaging: webpImaging, budget, capture: config.capture, log },
    { jobTimeoutMs: config.run.jobTimeoutMs }
  );
  return runJobs(
    { backend, runner, log },
    { windowMs: config.run.windowMs, hardStopMs: config.run.hardStopMs }
  );
}
function createJobsHandler(opts) {
  const write = opts.write ?? ((line) => {
    console.log(line);
  });
  let loaded = null;
  const load = () => {
    if (loaded) return loaded;
    try {
      loaded = { config: loadFunctionConfig(opts.env) };
    } catch (e) {
      loaded = { error: e instanceof FunctionConfigError ? e.problems : [errorMessage(e)] };
    }
    return loaded;
  };
  return async (req) => {
    const bootLog = createLogger({ write, base: { svc: "jobs-function" } });
    if (req.method !== "POST") return json(405, { error: "method_not_allowed" });
    const cfg = load();
    const expected = "config" in cfg ? cfg.config.cronSecret : opts.env["JOBS_CRON_SECRET"] ?? "";
    const given = req.headers.get(CRON_SECRET_HEADER) ?? "";
    if (!expected || !sameSecret(given, expected)) {
      bootLog.warn("run.unauthorized");
      return json(401, { error: "unauthorized" });
    }
    if ("error" in cfg) {
      bootLog.error("run.bad_config", { problems: cfg.error });
      return json(500, { error: "configuration", problems: cfg.error });
    }
    const config = cfg.config;
    const id = runId();
    const log = createLogger({
      level: config.logLevel,
      write,
      base: { svc: "jobs-function", run: id }
    });
    const inline = new URL(req.url).searchParams.get("wait") === "1" || !opts.waitUntil;
    const work = (async () => {
      log.info("run.start", {
        ...describeFunctionConfig(config),
        mode: inline ? "inline" : "background",
        ...opts.runtime ? { runtime: opts.runtime } : {}
      });
      try {
        const summary = await executeRun(config, log, opts.fetch);
        log.info("run.end", {
          ms: summary.ms,
          stoppedBy: summary.stoppedBy,
          hardStopped: summary.hardStopped,
          jobs: summary.jobs.length,
          results: summary.jobs.map((j) => `${j.kind}:${j.result}`)
        });
        return summary;
      } catch (e) {
        log.error("run.crashed", { error: errorMessage(e) });
        throw e;
      }
    })();
    if (inline) {
      try {
        return json(200, { run: id, ...await work });
      } catch (e) {
        return json(500, { run: id, error: errorMessage(e) });
      }
    }
    opts.waitUntil?.(work.catch(() => void 0));
    return json(202, { accepted: true, run: id });
  };
}
export {
  CRON_SECRET_HEADER,
  createJobsHandler
};
