/** Renders compat/RESULTS.md (or RESULTS-<host>.md for another CDN) from a suite run. */
import type { ProbeRecord } from './contract';
import type { CompatCase } from './packages';

export interface CdnTiming {
  /**
   * Sum over the case's CDN URLs, first request. For our CDN that is on an empty cache
   * (registry + extract + bundle); an external CDN may have them cached already.
   */
  coldMs: number;
  /** Same URLs again (our CDN: disk cache hit). */
  warmMs: number;
  bytes: number;
  urls: string[];
  error: string | null;
}

export interface CdnInfo {
  /** Base URL the runtime used. */
  url: string;
  /** True for @br/pkg-cdn started by the suite, false for an external CDN (`--cdn`). */
  own: boolean;
}

export interface CaseResult {
  case: CompatCase;
  pass: boolean;
  reason: string | null;
  cdn: CdnTiming;
  /** The CDN contract (compat/contract.ts) on the case's URLs and the modules behind them. */
  contract: { checked: number; problems: string[]; notes: string[] };
  buildMs: number;
  readyMs: number;
  consoleErrors: string[];
}

function median(xs: number[]): number {
  if (xs.length === 0) return NaN;
  const s = [...xs].sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 ? (s[mid] ?? NaN) : ((s[mid - 1] ?? 0) + (s[mid] ?? 0)) / 2;
}

function p95(xs: number[]): number {
  if (xs.length === 0) return NaN;
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.ceil(0.95 * s.length) - 1)] ?? NaN;
}

const ms = (n: number) => (Number.isFinite(n) ? n.toFixed(n < 10 ? 1 : 0) : '–');
const kb = (n: number) => (n > 0 ? (n / 1024).toFixed(n < 10 * 1024 ? 1 : 0) : '–');
const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\s+/g, ' ');
const short = (url: string, base: string) =>
  url.startsWith(base) ? url.slice(base.length) || '/' : url;

/** The React import-map table: what the CDN answered for each URL and the modules behind it. */
function contractTable(cdn: CdnInfo, records: readonly ProbeRecord[]): string[] {
  const lines = [
    '| URL | Depth | Status | Cache-Control | CORS | Vary | Type | Same-origin imports (shell finds) | Problems |',
    '|---|---|---|---|---|---|---|---|---|',
  ];
  for (const r of records) {
    lines.push(
      `| \`${cell(short(r.url, cdn.url))}\` | ${String(r.depth)} | ${r.status === null ? 'no answer' : String(r.status)} | ${cell(r.cacheControl ?? '–')} | ${cell(r.allowOrigin ?? '–')} | ${cell(r.vary ?? '–')} | ${cell(r.contentType ?? '–')} | ${String(r.imports.length)} (${String(r.shellFinds)}) | ${cell(r.problems.join('; ') || 'none')} |`,
    );
  }
  return lines;
}

export function renderResults(run: {
  cdn: CdnInfo;
  results: CaseResult[];
  react: CdnTiming;
  reactProbe: ProbeRecord[];
  bootMs: number;
}): string {
  const { cdn, results, react, reactProbe } = run;
  const passed = results.filter((r) => r.pass);
  const pct = (100 * passed.length) / results.length;
  const ok = results.filter((r) => r.cdn.error === null);
  const cold = ok.map((r) => r.cdn.coldMs);
  const warm = ok.map((r) => r.cdn.warmMs);
  const cdnName = cdn.own
    ? '`@br/pkg-cdn` resolving from the npm registry'
    : `the external CDN ${cdn.url}`;
  const lines: string[] = [];
  lines.push(
    cdn.own
      ? '# R1 package compatibility results'
      : `# R1 package compatibility results: ${new URL(cdn.url).host}`,
  );
  lines.push('');
  lines.push(
    `Generated by \`pnpm --filter @br/pkg-cdn compat${cdn.own ? '' : ` --cdn ${cdn.url}`}\` (apps/pkg-cdn/compat/run.ts). Do not edit by hand.`,
  );
  lines.push('');
  lines.push(
    `Each case is a small React app that imports the package, uses it and renders a marker. It runs through the real \`@br/runtime\` bundler worker, the sandbox shell (cross-site iframe + CSP) and ${cdnName}, in Chromium (Playwright). A case passes when the marker shows the expected text and the shell reported no runtime error.`,
  );
  lines.push('');
  lines.push(`- Date: ${new Date().toISOString().slice(0, 10)}`);
  lines.push(
    `- CDN: ${cdn.url}${cdn.own ? ' (@br/pkg-cdn, started by the suite)' : ' (external)'}`,
  );
  // A few packages have extra "variant" cases (a second usage style); the primary case of a
  // package is the one whose id is the package name.
  const primary = results.filter((r) => r.case.id === r.case.name);
  const primaryPassed = primary.filter((r) => r.pass).length;
  lines.push(
    `- **Cases passed: ${passed.length.toString()} / ${results.length.toString()} (${pct.toFixed(1)}%)**. R1 exit criterion (≥ 90% of the curated list): **${pct >= 90 ? 'met' : 'not met'}** (counting every case, variants included).`,
  );
  lines.push(
    `- Packages passed (primary case of each of the ${primary.length.toString()} packages): ${primaryPassed.toString()} / ${primary.length.toString()} (${((100 * primaryPassed) / primary.length).toFixed(1)}%). Variant cases probe a second usage style of a package already in the list.`,
  );
  const reactProblems = reactProbe.flatMap((r) => r.problems);
  const withProblems = results.filter((r) => r.contract.problems.length > 0);
  const checked = new Set([...reactProbe.map((r) => r.url), ...results.flatMap((r) => r.cdn.urls)])
    .size;
  lines.push(
    `- **CDN contract** (200 without a redirect, max-age ≥ 30 days, CORS, content type, imports only from the CDN's origin; compat/contract.ts): React import map ${reactProblems.length === 0 ? '**ok**' : `**${String(reactProblems.length)} problems**`} (${String(reactProbe.length)} URLs including the modules behind them); cases with problems: ${String(withProblems.length)} / ${String(results.length)}. About ${String(checked)} distinct URLs.`,
  );
  const notes = [
    ...new Set([
      ...reactProbe.flatMap((r) => r.notes),
      ...results.flatMap((r) => r.contract.notes),
    ]),
  ];
  if (notes.length > 0) {
    lines.push(
      `- Contract notes (not problems): ${notes
        .slice(0, 8)
        .map((n) => `\`${cell(n)}\``)
        .join(', ')}${notes.length > 8 ? ', …' : ''}.`,
    );
  }
  const first = cdn.own ? 'cold' : 'first request';
  const second = cdn.own ? 'warm' : 'second request';
  lines.push(
    `- React import-map modules (react, react/jsx-runtime, react/jsx-dev-runtime, react-dom, react-dom/client): ${first} ${ms(react.coldMs)} ms, ${second} ${ms(react.warmMs)} ms, ${kb(react.bytes)} KB.`,
  );
  lines.push(
    cdn.own
      ? `- CDN time per case (sum of the case's package URLs; cold = empty cache: packuments + tarballs + extract + bundle): median cold ${ms(median(cold))} ms, p95 cold ${ms(p95(cold))} ms, max cold ${ms(Math.max(...cold))} ms; median warm ${ms(median(warm))} ms, p95 warm ${ms(p95(warm))} ms.`
      : `- CDN time per case (sum of the case's package URLs; the first request may already be cached by the CDN): median first ${ms(median(cold))} ms, p95 first ${ms(p95(cold))} ms, max first ${ms(Math.max(...cold))} ms; median second ${ms(median(warm))} ms, p95 second ${ms(p95(warm))} ms.`,
  );
  lines.push(
    `- In-browser: esbuild-wasm worker cold start ${ms(run.bootMs)} ms; per case, build median ${ms(median(results.map((r) => r.buildMs).filter((n) => n > 0)))} ms, build → ready median ${ms(median(results.map((r) => r.readyMs).filter((n) => n > 0)))} ms (module download + evaluate).`,
  );
  lines.push(
    cdn.own
      ? '- Timings are from one run in a cloud container (registry over the internet, localhost CDN, no HTTP compression); treat them as relative.'
      : '- Timings are from one run (CDN over the internet); treat them as relative.',
  );
  lines.push('');
  const failed = results.filter((r) => !r.pass);
  if (failed.length > 0) {
    lines.push('## Failures');
    lines.push('');
    lines.push('| Package | Version | Reason |');
    lines.push('|---|---|---|');
    for (const r of failed) {
      lines.push(`| ${r.case.id} | ${r.case.version} | ${cell(r.reason ?? '')} |`);
    }
    lines.push('');
  }
  lines.push('## CDN contract: the React import map');
  lines.push('');
  lines.push(
    'Every import-map URL and every module it imports from the CDN (depth 1+: what the browser loads behind the entry URL). The sandbox shell warms these into the HTTP cache and needs them to stay there through an outage (T-032), from the origin its CSP allows (T-035).',
  );
  lines.push('');
  lines.push(...contractTable(cdn, reactProbe));
  lines.push('');
  if (withProblems.length > 0) {
    lines.push('## CDN contract problems by case');
    lines.push('');
    lines.push('| Package | Problems |');
    lines.push('|---|---|');
    for (const r of withProblems) {
      lines.push(
        `| ${r.case.id} | ${cell(r.contract.problems.slice(0, 5).join('; '))}${r.contract.problems.length > 5 ? ` (+${String(r.contract.problems.length - 5)} more)` : ''} |`,
      );
    }
    lines.push('');
  }
  lines.push('## All cases');
  lines.push('');
  lines.push(
    `${cdn.own ? 'Cold/Warm' : 'First/Second'} ms and KB cover the URLs the app imports directly (what \`cdn-rewrite\` emits), not the peer or self-subpath modules those import in turn (e.g. \`zustand\` re-exports \`/zustand@…/vanilla\`). Contract counts every URL checked for the case, those modules included. Build ms = esbuild-wasm build in the worker; Ready ms = build start → the shell reports the module evaluated.`,
  );
  lines.push('');
  lines.push(
    `| # | Package | Version | Category | Result | ${cdn.own ? 'Cold' : 'First'} ms | ${cdn.own ? 'Warm' : 'Second'} ms | KB | Build ms | Ready ms | Contract | What the smoke app checks | Notes |`,
  );
  lines.push('|---|---|---|---|---|---|---|---|---|---|---|---|---|');
  results.forEach((r, i) => {
    const notes: string[] = [];
    if (r.case.deps)
      notes.push(
        `with ${Object.entries(r.case.deps)
          .map(([n, v]) => `${n}@${v}`)
          .join(', ')}`,
      );
    if (r.consoleErrors.length > 0)
      notes.push(`console.error: ${r.consoleErrors[0]?.slice(0, 120) ?? ''}`);
    const contract =
      r.contract.problems.length > 0
        ? `**${String(r.contract.problems.length)} problems**`
        : `ok (${String(r.contract.checked)})`;
    lines.push(
      `| ${(i + 1).toString()} | ${r.case.id} | ${r.case.version} | ${r.case.category} | ${r.pass ? 'pass' : '**FAIL**'} | ${ms(r.cdn.coldMs)} | ${ms(r.cdn.warmMs)} | ${kb(r.cdn.bytes)} | ${ms(r.buildMs)} | ${ms(r.readyMs)} | ${contract} | ${cell(r.case.checks)} | ${cell(notes.join('; '))} |`,
    );
  });
  lines.push('');
  return `${lines.join('\n')}\n`;
}
