/** Renders compat/RESULTS.md from a suite run. */
import type { CompatCase } from './packages';

export interface CdnTiming {
  /** Sum over the case's CDN URLs, first request on an empty cache (registry + extract + bundle). */
  coldMs: number;
  /** Same URLs again (disk cache hit). */
  warmMs: number;
  bytes: number;
  urls: string[];
  error: string | null;
}

export interface CaseResult {
  case: CompatCase;
  pass: boolean;
  reason: string | null;
  cdn: CdnTiming;
  buildMs: number;
  readyMs: number;
  consoleErrors: string[];
}

function median(xs: number[]): number {
  if (xs.length === 0) return NaN;
  const s = [...xs].sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 ? (s[mid] ?? NaN) : ((s[mid - 1] ?? 0) + (s[mid] ?? 0)) / 2;
}

function p95(xs: number[]): number {
  if (xs.length === 0) return NaN;
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.ceil(0.95 * s.length) - 1)] ?? NaN;
}

const ms = (n: number) => (Number.isFinite(n) ? n.toFixed(n < 10 ? 1 : 0) : '–');
const kb = (n: number) => (n > 0 ? (n / 1024).toFixed(n < 10 * 1024 ? 1 : 0) : '–');
const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\s+/g, ' ');

export function renderResults(run: {
  results: CaseResult[];
  react: CdnTiming;
  bootMs: number;
}): string {
  const { results, react } = run;
  const passed = results.filter((r) => r.pass);
  const pct = (100 * passed.length) / results.length;
  const ok = results.filter((r) => r.cdn.error === null);
  const cold = ok.map((r) => r.cdn.coldMs);
  const warm = ok.map((r) => r.cdn.warmMs);
  const lines: string[] = [];
  lines.push('# R1 package compatibility results');
  lines.push('');
  lines.push(
    'Generated by `pnpm --filter @br/pkg-cdn compat` (apps/pkg-cdn/compat/run.ts). Do not edit by hand.',
  );
  lines.push('');
  lines.push(
    'Each case is a small React app that imports the package, uses it and renders a marker. It runs through the real `@br/runtime` bundler worker, the sandbox shell (cross-site iframe + CSP) and `@br/pkg-cdn` resolving from the npm registry, in Chromium (Playwright). A case passes when the marker shows the expected text and the shell reported no runtime error.',
  );
  lines.push('');
  lines.push(`- Date: ${new Date().toISOString().slice(0, 10)}`);
  // A few packages have extra "variant" cases (a second usage style); the primary case of a
  // package is the one whose id is the package name.
  const primary = results.filter((r) => r.case.id === r.case.name);
  const primaryPassed = primary.filter((r) => r.pass).length;
  lines.push(
    `- **Cases passed: ${passed.length.toString()} / ${results.length.toString()} (${pct.toFixed(1)}%)**. R1 exit criterion (≥ 90% of the curated list): **${pct >= 90 ? 'met' : 'not met'}** (counting every case, variants included).`,
  );
  lines.push(
    `- Packages passed (primary case of each of the ${primary.length.toString()} packages): ${primaryPassed.toString()} / ${primary.length.toString()} (${((100 * primaryPassed) / primary.length).toFixed(1)}%). Variant cases probe a second usage style of a package already in the list.`,
  );
  lines.push(
    `- React import-map modules (react, react/jsx-runtime, react-dom, react-dom/client): cold ${ms(react.coldMs)} ms, warm ${ms(react.warmMs)} ms, ${kb(react.bytes)} KB.`,
  );
  lines.push(
    `- CDN time per case (sum of the case's package URLs; cold = empty cache: packuments + tarballs + extract + bundle): median cold ${ms(median(cold))} ms, p95 cold ${ms(p95(cold))} ms, max cold ${ms(Math.max(...cold))} ms; median warm ${ms(median(warm))} ms, p95 warm ${ms(p95(warm))} ms.`,
  );
  lines.push(
    `- In-browser: esbuild-wasm worker cold start ${ms(run.bootMs)} ms; per case, build median ${ms(median(results.map((r) => r.buildMs).filter((n) => n > 0)))} ms, build → ready median ${ms(median(results.map((r) => r.readyMs).filter((n) => n > 0)))} ms (warm CDN, module download + evaluate).`,
  );
  lines.push(
    '- Timings are from one run in a cloud container (registry over the internet, localhost CDN, no HTTP compression); treat them as relative.',
  );
  lines.push('');
  const failed = results.filter((r) => !r.pass);
  if (failed.length > 0) {
    lines.push('## Failures');
    lines.push('');
    lines.push('| Package | Version | Reason |');
    lines.push('|---|---|---|');
    for (const r of failed) {
      lines.push(`| ${r.case.id} | ${r.case.version} | ${cell(r.reason ?? '')} |`);
    }
    lines.push('');
  }
  lines.push('## All cases');
  lines.push('');
  lines.push(
    'Cold/Warm ms and KB cover the URLs the app imports directly (what `cdn-rewrite` emits), not the peer or self-subpath modules those import in turn (e.g. `zustand` re-exports `/zustand@…/vanilla`). Build ms = esbuild-wasm build in the worker; Ready ms = build start → the shell reports the module evaluated.',
  );
  lines.push('');
  lines.push(
    '| # | Package | Version | Category | Result | Cold ms | Warm ms | KB | Build ms | Ready ms | What the smoke app checks | Notes |',
  );
  lines.push('|---|---|---|---|---|---|---|---|---|---|---|---|');
  results.forEach((r, i) => {
    const notes: string[] = [];
    if (r.case.deps)
      notes.push(
        `with ${Object.entries(r.case.deps)
          .map(([n, v]) => `${n}@${v}`)
          .join(', ')}`,
      );
    if (r.consoleErrors.length > 0)
      notes.push(`console.error: ${r.consoleErrors[0]?.slice(0, 120) ?? ''}`);
    lines.push(
      `| ${(i + 1).toString()} | ${r.case.id} | ${r.case.version} | ${r.case.category} | ${r.pass ? 'pass' : '**FAIL**'} | ${ms(r.cdn.coldMs)} | ${ms(r.cdn.warmMs)} | ${kb(r.cdn.bytes)} | ${ms(r.buildMs)} | ${ms(r.readyMs)} | ${cell(r.case.checks)} | ${cell(notes.join('; '))} |`,
    );
  });
  lines.push('');
  return `${lines.join('\n')}\n`;
}
