/**
 * Bundles the `jobs` Edge Function's code (src/edge/entry.ts and what it imports from this
 * package, @br/sandbox-shell and @br/runtime) into one ES module for Deno:
 * supabase/functions/jobs/core.js. Platform-neutral: a Node built-in in the graph fails the
 * build. Paths in the output are relative to this package, so the output is the same on
 * every machine (test/function-bundle.test.ts compares it with the committed file).
 */
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

export const PACKAGE_DIR = fileURLToPath(new URL('../', import.meta.url));
export const FUNCTION_BUNDLE = fileURLToPath(
  new URL('../../../supabase/functions/jobs/core.js', import.meta.url),
);

const BANNER = `// GENERATED by \`pnpm --filter @br/capture-worker build:function\` from
// apps/capture-worker/src/edge/entry.ts (T-034). Do not edit; change the sources and rebuild.
// A unit test (apps/capture-worker/test/function-bundle.test.ts) fails when this is stale.`;

export async function bundleFunction(): Promise<string> {
  const result = await build({
    absWorkingDir: PACKAGE_DIR,
    entryPoints: ['src/edge/entry.ts'],
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    mainFields: ['module', 'main'],
    resolveExtensions: ['.ts', '.js', '.mjs'],
    write: false,
    metafile: true,
    charset: 'utf8',
    legalComments: 'none',
    banner: { js: BANNER },
    logLevel: 'silent',
  });
  const node = Object.keys(result.metafile.inputs).filter((p) => p.startsWith('node:'));
  if (node.length > 0) throw new Error(`Node built-ins in the function bundle: ${node.join(', ')}`);
  const out = result.outputFiles[0];
  if (!out) throw new Error('esbuild produced no output');
  return out.text;
}
